export const tmdbEndpoints = {
  airingTodayTv: '/tv/airing_today',
  animeTv: '/discover/tv',
  discoverMovie: '/discover/movie',
  discoverTv: '/discover/tv',
  movieDetails: (tmdbId: number) => `/movie/${tmdbId}`,
  movieVideos: (tmdbId: number) => `/movie/${tmdbId}/videos`,
  nowPlayingMovies: '/movie/now_playing',
  onTheAirTv: '/tv/on_the_air',
  popularMovies: '/movie/popular',
  popularTv: '/tv/popular',
  searchMulti: '/search/multi',
  seasonDetails: (tmdbId: number, season: number) => `/tv/${tmdbId}/season/${season}`,
  topRatedMovies: '/movie/top_rated',
  topRatedTv: '/tv/top_rated',
  trending: '/trending/all/day',
  trendingMovies: '/trending/movie/day',
  trendingTv: '/trending/tv/day',
  tvDetails: (tmdbId: number) => `/tv/${tmdbId}`,
  tvVideos: (tmdbId: number) => `/tv/${tmdbId}/videos`,
  upcomingMovies: '/movie/upcoming',
} as const;
